### ISSUE TITLE
Treemap panel not working with Grafana version 8.0.6

### ISSUE THREAD

**Issue by S-Namita** [marcusolsson/grafana-treemap-panel#23]
<img width="1275" alt="Screen Shot 2021-08-31 at 11 47 40 AM" src="https://user-images.githubusercontent.com/58048690/131575279-8fc42191-2806-43a3-b1c9-32a49ab0824e.png">
Getting "Object() is not a function" error, this panel was working fine before Grafana version upgrade.
Please advise if this can be fixed or would downgrade be my option option?

**Comment by marcusolsson** [comment]
Hey! I just published v0.9.1 which should work better with Grafana 8. Let me know if the problem remains!
